# Generated by Django 3.1.7 on 2022-01-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Herbal_Life', '0005_event_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Date', models.DateField()),
                ('Desc', models.CharField(max_length=150)),
                ('Address', models.CharField(max_length=150)),
            ],
        ),
    ]
